### ISSUE TITLE
Error parsing logs: "ZeroDivisionError: float division by zero"

### ISSUE THREAD

**Issue by zequeira** [logpai/Drain3#65]
Hi,
I'm using Drain3 to parse some logs and sometimes I get the following error:

**Traceback (most recent call last):
  File "C:\+\envs\+\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-11de0f070b31>", line 13, in <cell line: 11>
    result = template_miner.add_log_message(msg)
  File "C:\+\envs\+\lib\site-packages\drain3\template_miner.py", line 146, in add_log_message
    self.profiler.report(self.config.profiling_report_sec)
  File "C:\+\envs\+\lib\site-packages\drain3\simple_profiler.py", line 112, in report
    text = os.linesep.join(lines)
  File "C:\+\envs\+\lib\site-packages\drain3\simple_profiler.py", line 111, in <lambda>
    lines = map(lambda it: it.to_string(enclosing_time_sec, include_batch_rates), sorted_sections)
  File "C:\+\envs\+\lib\site-packages\drain3\simple_profiler.py", line 135, in to_string
    samples_per_sec = f"{self.sample_count / self.total_time_sec: 15,.2f}"
ZeroDivisionError: float division by zero**

any help would be appreciated.

**Comment by Superskyyy** [comment]
I guess the code didn't start and enclose the last section, which I think is probably this
```
template_miner.profiler.start_section('print_tree')
template_miner.drain.print_tree()
template_miner.profiler.end_section('print_tree')

template_miner.profiler.report(period_sec=0)
```
So the profiler took the wrong section `total` which is already done profiling. 

Can you confirm please? @davidohana

**Comment by davidohana** [comment]
@zequeira  This seems like a bug in the profiler, when trying to measure the time of a very short operation, the total time is 0.  Fixed in latest version 0.9.11 (hopefully), please check.

**Comment by davidohana** [comment]
@Superskyyy I don't see any profiling of `print_tree` in the codebase, can you specify the exact lines?

**Comment by Superskyyy** [comment]
This is fixed and closing.
