### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by chong1ha** [logpai/Drain3#95]
Hi,

I saw a page within GitHub Packages about supporting Apache Maven registry, and I was wondering what this means.

As far as I understand, there was no code or setting found for direct interworking with Java inside the project. Nevertheless, seeing it delivered through the Maven registry in GitHub Packages raised questions about how this project could be used in a Java environment, or if it could be added directly as Maven dependency in the Java project.

https://github.com/logpai/Drain3/packages

I'm trying to make sure because I might have misunderstood the contents of the page.

Is the lopai/Drain3 project available in Java project? 

Thank you.

**Comment by Superskyyy** [comment]
The packaging is merely a github page showing "possibilities", it really has nothing to do with Drain3. Drain3 hasn't setup a packaging through this way so the possibilities are by default shown by GitHub. If you  create a repo you will see those too.

**Comment by Superskyyy** [comment]
Although in the future I might support drain serving inside a docker container. See R3 that is based on Drain3 https://github.com/skyapm/R3
